version: '3'

services:
  web:
    ports:
      - 80:8080

  postgres-test:
    image: postgres:13
    environment:
      - POSTGRES_DB=app_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=laraveldocker

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

  redis:
    ports:
      - 6379:6379
