version: '3'

services:
  mailcatcher:
    restart: unless-stopped

  app:
    restart: unless-stopped

  worker:
    restart: unless-stopped

  postgres:
    restart: unless-stopped

  redis:
    restart: unless-stopped
