version: '3'

services:
  postgres-test:
    image: postgres:13
    environment:
      - POSTGRES_DB=app_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=laraveldocker

  redis:
    ports:
      - 6379:6379
