version: '3'

services:
  web:
    ports:
      - 8080:8080
    restart: unless-stopped

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
    restart: unless-stopped

  app:
    restart: unless-stopped

  worker:
    restart: unless-stopped
  
  postgres:
    restart: unless-stopped

  redis:
    restart: unless-stopped
