version: '3'

services:
  mailcatcher:
    restart: unless-stopped

  app:
    restart: unless-stopped

  worker:
    restart: unless-stopped

  postgres:
    restart: unless-stopped
    ports:
      - "5432:5432"

  redis:
    restart: unless-stopped
