version: '3'

services:
  postgres:
    ports:
      - "5432:5432"

  postgres-test:
    extends:
      file: docker-compose.yml
      service: postgres
    tmpfs:
      - /var/lib/postgresql/data

  redis:
    ports:
      - 6379:6379
