version: '3'

volumes:
  app-postgres-data:
    driver: local

services:
  app:
    image: webdevops/php-nginx:8.1-alpine
    volumes:
      - ./project:/app
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_MEMORY_LIMIT=64M
    ports:
      - "80:80"

  postgres:
    image: postgres:15-alpine
    volumes:
      - app-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=laraveldocker

  redis:
    image: redis:5.0
    command: --appendonly no

  worker:
    build: environment/docker/worker/.
    volumes:
      - ./project:/app
    environment:
      - PHP_MEMORY_LIMIT=64M

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
