name: Styleguide Check (Pint)

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**.php'
      - 'phpunit.xml'
      - '.github/workflows/style.yml'
      - 'composer.lock'

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@0.1.0
        with:
          configPath: "project/pint.json"
          verboseMode: true
          testMode: true
